public enum TutorialCondicion
{
    Manual,
    ParcelaClickeada,
    PlantarClickeado,
    CultivoSeleccionado,
    EstudiarClickeado,
    MejorarClickeado,
    EsperarClickeado,
    EventoAbierto,
    EventoResuelto,
    CatalogoAbierto,
    CatalogoCerrado,
    HistorialAbierto,
    DetalleHistorialVisto,
    CicloAvanzado,
    ReporteCerrado,
    EventoCerrado
}
